# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: lint-dockerfile
        name: Lint Dockerfile
        entry: make lint-dockerfile
        language: system
        files: \.yml$

      - id: lint-yaml
        name: Lint YAML
        entry: make lint-yaml
        language: system
        files: \.yml$
