name: CI

on: [push, pull_request]

env:
  TEST_IMAGE_NAME: helm-chart-linting-tools:${{ github.sha }}
  PROD_IMAGE_NAME: brpaz/helm-chart-linting-tools:latest

jobs:
  lint:
    name: "Lint Dockerfile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: brpaz/hadolint-action@master

  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . -t $TEST_IMAGE_NAME
      - name: Container Structure test
        uses: brpaz/structure-tests-action@master
        with:
          image: ${{ env.TEST_IMAGE_NAME }}
      - name: Crate image artifact
        run: docker save -o image.tar.gz $TEST_IMAGE_NAME
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: image
          path: image.tar.gz

  publish:
    name: "Publish Release"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v1
        with:
          name: image
      - name: Load Docker image
        run: docker load < image/image.tar.gz
      - run: docker tag $TEST_IMAGE_NAME $PROD_IMAGE_NAME
      - uses: actions/checkout@master
      - name: Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @eclass/semantic-release-docker
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
